version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: visaurus
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"